# The purpose of this program is to create an API key & request that is encoded based on a specific seed, either user defined, or autogenerated
# This allows you to provide base64 endcoded API keys and data, with no authentication request being submitted.
# Send two packets of data, an encoded string of data, and your base64 encoded seed. For added security, an API key could be used.
